import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {WebSocket} from 'ws';
const origin='http://127.0.0.1:3147';
const wait=(ws,type)=>new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{ws.off('message',listen);reject(Error('Timed out waiting for '+type));},4000);const listen=raw=>{const m=JSON.parse(raw);if(m.type===type){clearTimeout(timeout);ws.off('message',listen);resolve(m);}};ws.on('message',listen);});
async function connect(data){const ws=new WebSocket(origin.replace('http','ws')+'/play');await new Promise((ok,no)=>{ws.once('open',ok);ws.once('error',no);});const result=wait(ws,data.expect||'joined');ws.send(JSON.stringify({type:'join',...data}));return{ws,result:await result};}
test('real WebSocket rooms, six players, authoritative state and admin access',async t=>{const proc=spawn(process.execPath,['server.mjs'],{cwd:new URL('../',import.meta.url),env:{...process.env,PORT:'3147',ADMIN_PASSWORD:'pakiboys'},stdio:['ignore','pipe','pipe']});let stderr='';proc.stderr.on('data',d=>stderr+=d);t.after(()=>proc.kill());await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Server failed: '+stderr)),6000);proc.stdout.on('data',()=>{clearTimeout(timer);resolve();});proc.once('error',reject);});const clients=[];t.after(()=>clients.forEach(c=>c.close()));const first=await connect({create:true,name:'Host',settings:{mode:'deathmatch'}});clients.push(first.ws);const code=first.result.code;assert.match(code,/^[A-F0-9]{6}$/);for(let i=1;i<6;i++){const c=await connect({code,name:'Player '+i,loadout:{primary:'awp'}});clients.push(c.ws);}const full=await connect({code,name:'Overflow',expect:'error'});clients.push(full.ws);assert.match(full.result.message,/full/);const s=await wait(first.ws,'state');assert.equal(s.players.length,6);assert.ok(s.players.filter(p=>p.name.startsWith('Player')).every(p=>p.weapon==='awp'));
 const before=s.players.find(p=>p.id===first.result.id);first.ws.send(JSON.stringify({type:'input',side:1,forward:0,yaw:0,pitch:0}));await new Promise(r=>setTimeout(r,300));const after=await wait(first.ws,'state');assert.notEqual(after.players.find(p=>p.id===first.result.id).x,before.x);
 let res=await fetch(origin+'/api/admin');assert.equal(res.status,401);res=await fetch(origin+'/api/admin/login',{method:'POST',body:JSON.stringify({password:'wrong'})});assert.equal(res.status,401);res=await fetch(origin+'/api/admin/login',{method:'POST',body:JSON.stringify({password:'pakiboys'})});const {token}=await res.json();assert.ok(token);const headers={'Content-Type':'application/json',Authorization:'Bearer '+token};res=await fetch(origin+'/api/admin',{headers});const rooms=await res.json();assert.equal(rooms.rooms[0].players.length,6);res=await fetch(origin+'/api/admin',{method:'POST',headers,body:JSON.stringify({code,action:'configure',settings:{map:'harbor',maxHP:150}})});assert.equal(res.status,200);const changed=await wait(first.ws,'state');assert.equal(changed.settings.map,'harbor');assert.equal(changed.players[0].hp,150);
 res=await fetch(origin+'/api/admin',{method:'POST',headers,body:JSON.stringify({code,action:'configure',settings:{mode:'duel'}})});assert.equal(res.status,400);
 const kicked=clients[5];const closed=new Promise(r=>kicked.once('close',(code)=>r(code)));res=await fetch(origin+'/api/admin',{method:'POST',headers,body:JSON.stringify({code,action:'kick',playerId:changed.players[5].id})});assert.equal(res.status,200);assert.equal(await closed,4001);
 res=await fetch(origin+'/%2e%2e/server.mjs');assert.notEqual(res.status,200);res=await fetch(origin+'/.env');assert.equal(res.status,403);});
